### ISSUE TITLE
Why do some genes have zero log2 RSEM values

### ISSUE THREAD

**Issue by hummingbirdbio** [wenjie1991/TSVdb#22]
E.g. SCN5A?

**Comment by wenjie1991** [comment]
I have checked the SCN5A in Colon cancer and Esophagus cancer datasets. And confirmed that "almost every isoform expression of the gene SCN5A is 0". 

By downloading the original data from the "Download Data" link in the top-left of the page, I found the isoform expression values were empty. However, most of the genes did not be affected by this problem. So I suppose the data source from TCGA does not contain the SCN5A isoform expression data.

I do not know if I have solved your problem. Free feel to contact me if you have any question about this tool.

**Comment by hummingbirdbio** [comment]
Thanks, that's great. I just wanted to make sure it was a TCGA data feature rather than a bug.

Konrad Paszkiewicz, PhD
Chief Technology Officer
Hummingbird Bioscience Pte. Ltd.



NOTICE:  The information contained in this email and any document attached hereto is intended only for the named recipient(s). If you are not the intended recipient, nor the employee or agent responsible for delivering this message in confidence to the intended recipient(s), you are hereby notified that you have received this transmittal in error, and any review, dissemination, distribution or copying of this transmittal or its attachments is strictly prohibited. If you have received this transmittal and/or attachments in error, please notify me immediately by reply e-mail and then delete this message, including any attachments. Thank you for your cooperation.




________________________________
