### ISSUE TITLE
How to get specific sequence information by UCSC transcript ID

### ISSUE THREAD

**Issue by sunsong95** [wenjie1991/TSVdb#28]
I can get the expression atlas of the transcript from the TSVdb website, such as uc010fzs.3, but it seems that the UCSC transcript ID has been rarely used. Here are my questions:

1. I'd like to know how to match UCSC transcript ID to a specific sequence.
2. Does TCGA have access to ENSTXXXXXXXX transcript expression information without permission ?

Thanks！

**Comment by wenjie1991** [comment]
Hi,
Sorry, I do not know if there is an easy way to convert the UCSC id to ENSEMBL id.
But you can find the NCBI id in UCSC Genome Browser corresponding to UCSC id:
![2020-01-16 17-38-15 2020-01-16 17_39_09](https://user-images.githubusercontent.com/6602710/72544195-2de5d980-3887-11ea-986b-46066f47af76.gif)
We downloaded the TCGA data from (http://firebrowse.org/). I think they do not provide the ENSEMBL id version, but you can have a try.
