### ISSUE TITLE
Does not work transcript picture for some genes

### ISSUE THREAD

**Issue by andreyurch** [wenjie1991/TSVdb#29]
I tried 3 different browsers.
Cutaneous melanoma, STK19

<img width="2298" alt="Screenshot 2020-05-06 at 16 15 39" src="https://user-images.githubusercontent.com/16365207/81187830-d5ad2180-8fb4-11ea-8c88-56fe0888cf15.png">

**Comment by wenjie1991** [comment]
Hi @andreyurch,
Thanks for reporting this bug! 

The gene STK19 has two chromosome location: [chr6](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr6%3A31940079%2D31950696&hgsid=833523905_No7MFA1DnFJBrfdTBSoA5cvsVbAX) and [chr6_dbb_hap3](https://genome.ucsc.edu/cgi-bin/hgTracks?db=hg19&lastVirtModeType=default&lastVirtModeExtraState=&virtModeType=default&virtMode=0&nonVirtPosition=&position=chr6_dbb_hap3%3A3225662%2D3236277&hgsid=833541219_7KRj7Xo9vTD9cjKyFHxdyfMBVtiR). The TSVdb could not deal with those two loations of STK19, thus the bug apeared.

And as the TCGA data only cover the `chr6`. Therefore, we only include the primary reference `chr6` to avoid this error.
https://github.com/wenjie1991/TSVdb/commit/4acd2aa0ddb374c709b83e493cb7e7a871dabce6

**Comment by andreyurch** [comment]
A gene can not be located in two different locations. Yes, there are different annotations, but you can choose a single, the canonical one and visualize it. Why no to correctly visualize transcripts on the chr6?

**Comment by wenjie1991** [comment]
> Why no to correctly visualize transcripts on the chr6?

Hi @andreyurch. That's what we have done. Maybe I did not make it clear in my last comment. 
We have updated the code, see commit https://github.com/wenjie1991/TSVdb/commit/4acd2aa0ddb374c709b83e493cb7e7a871dabce6. Now only the canonical chromosomes are used. The case you described has been solved.

**Comment by andreyurch** [comment]
I apologize for the misunderstanding. Thank you very much!

**Comment by wenjie1991** [comment]
You are welcome! 
Again, thank you for letting us know the bug!
